apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: easysplit
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: easysplit

