apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - db/service.yaml
  - db/statefulset.yaml
  - sealed-secrets/db-credentials.yaml

namespace: easysplit

